### PR TITLE
Post by user

### LINKED ISSUE #21: Post issue in Github on behalf of Telegram user
Post the issue in Github on behalf of the user that sent the original message in telegram so that the posting user can get incentive.

Mapping between a user's telegram and GitHub will be added by https://github.com/ubiquity/telegram-ubiquibot/issues/4 , which is needed for this issue.

- context https://github.com/ubiquity/telegram-ubiquibot/pull/1#discussion_r1288727113

### PR DESCRIPTION
**Pull request by seprintour**
Resolves #21

### CODE REVIEW

**Comment by 0x4007** [comment]
Can you post a link to a Telegram channel that we can test it with?

**Comment by seprintour** [comment]
> Can you post a link to a Telegram channel that we can test it with?

I've messaged you in Tester GPT - 2

**Comment by 0x4007** [comment]
https://t.me/c/1558587400/1/463

Link required here for reviewers.

**Review by pavlovcik — APPROVED** [review]
I tested the flow with mostly success [here](https://github.com/ubiquibot/production/issues/58). 
- However it did not automatically add the estimated time label. I'm pretty sure I added that to a previous specification.
- Also it does not seem to support topics. Only entire groups. 

There's a handful of small adjustments I'd like that we can roll into new task(s) after merging in the current pull request:

- Issue titles should be Title Case and no punctuation at the end
- No more block quote for the message extracted from telegram (we ignore blockquotes for comment incentives. Just write with normal text.
- "[ View Conversation Context ]" to "[ View on Telegram ]"
- The bot should not post real messages to the group chat, but instead post "private messages" inside of the group chat, which is only visible to the person who invoked the bot. I've seen this Telegram bot capability with bots that send new users private CAPTCHAs when they join large group chats. The user is able to interact with the bot in a private manner inside of the context of the group chat (nobody else sees the messages)
- Enable a "force task to write to GitHub" capability by directly tagging the bot inside of the message to force recording it on GitHub (this is useful for edge cases where the bot doesn't automatically pick up a message as a task)

**Pull request merged**
